import React from 'react';
import { TITLE_DATA, CONTENT_DATA } from './data/PrivacyData';
import InfoLayout from '../../../layouts/InfoLayout';

export default function Privacy() {
    return (
        <InfoLayout titleData={TITLE_DATA} headTitle={TITLE_DATA.header}>
            <>
                <h2>{CONTENT_DATA.purposeSubtitle}</h2>
                <p>{CONTENT_DATA.purposeTextOne}</p>
                <p>{CONTENT_DATA.purposeTextTwo}</p>
                <p>{CONTENT_DATA.purposeTextThree}</p>
                <p>{CONTENT_DATA.purposeTextFour}</p>
                <h3>{CONTENT_DATA.importantInformationSubtitle}</h3>
                <p>{CONTENT_DATA.importantInformationTextOne}</p>
                <h4>{CONTENT_DATA.importantInformationSubtitleTwo}</h4>
                <p>{CONTENT_DATA.importantInformationTextTwo}</p>
                <h4>{CONTENT_DATA.importantInformationSubtitleThree}</h4>
                <p>{CONTENT_DATA.importantInformationTextThree}</p>
                <h3>{CONTENT_DATA.informationCollectSubtitle}</h3>
                <p>{CONTENT_DATA.informationCollectTextOne}</p>
                <p>{CONTENT_DATA.informationCollectTextTwo}</p>
                <h4>{CONTENT_DATA.identitySubtitle}</h4>
                <ul>
                    <li>{CONTENT_DATA.identityTextOne}</li>
                    <li>{CONTENT_DATA.identityTextTwo}</li>
                    <li>{CONTENT_DATA.identityTextThree}</li>
                    <li>{CONTENT_DATA.identityTextFour}</li>
                    <li>{CONTENT_DATA.identityTextFive}</li>
                    <li>{CONTENT_DATA.identityTextSix}</li>
                    <li>{CONTENT_DATA.identityTextSeven}</li>
                    <li>{CONTENT_DATA.identityTextEight}</li>
                    <li>{CONTENT_DATA.identityTextNine}</li>
                </ul>
                <h4>{CONTENT_DATA.socialSubtitle}</h4>
                <ul>
                    <li>{CONTENT_DATA.socialTextOne}</li>
                    <li>{CONTENT_DATA.socialTextTwo}</li>
                    <li>{CONTENT_DATA.socialTextThree}</li>
                    <li>{CONTENT_DATA.socialTextFour}</li>
                    <li>{CONTENT_DATA.socialTextFive}</li>
                    <li>{CONTENT_DATA.socialTextSix}</li>
                    <li>{CONTENT_DATA.socialTextSeven}</li>
                </ul>
                <h4>{CONTENT_DATA.contactSubtitle}</h4>
                <ul>
                    <li>{CONTENT_DATA.contactTextOne}</li>
                    <li>{CONTENT_DATA.contactTextTwo}</li>
                    <li>{CONTENT_DATA.contactTextThree}</li>
                    <li>{CONTENT_DATA.contactTextFour}</li>
                    <li>{CONTENT_DATA.contactTextFive}</li>
                    <li>{CONTENT_DATA.contactTextSix}</li>
                    <li>{CONTENT_DATA.contactTextSeven}</li>
                </ul>
                <h4>{CONTENT_DATA.financialSubtitle}</h4>
                <ul>
                    <li>{CONTENT_DATA.financialTextOne}</li>
                    <li>{CONTENT_DATA.financialTextTwo}</li>
                    <li>{CONTENT_DATA.financialTextThree}</li>
                    <li>{CONTENT_DATA.financialTextFour}</li>
                    <li>{CONTENT_DATA.financialTextFive}</li>
                    <li>{CONTENT_DATA.financialTextSix}</li>
                    <li>{CONTENT_DATA.financialTextSeven}</li>
                </ul>
                <h4>{CONTENT_DATA.transactionalSubtitle}</h4>
                <ul>
                    <li>{CONTENT_DATA.transactionalTextOne}</li>
                    <li>{CONTENT_DATA.transactionalTextTwo}</li>
                    <li>{CONTENT_DATA.transactionalTextThree}</li>
                    <li>{CONTENT_DATA.transactionalTextFour}</li>
                    <li>{CONTENT_DATA.transactionalTextFive}</li>
                    <li>{CONTENT_DATA.transactionalTextSix}</li>
                    <li>{CONTENT_DATA.transactionalTextSeven}</li>
                    <li>{CONTENT_DATA.transactionalTextEight}</li>
                    <li>{CONTENT_DATA.transactionalTextNine}</li>
                    <li>{CONTENT_DATA.transactionalTextTen}</li>
                    <li>{CONTENT_DATA.transactionalTextEleven}</li>
                    <li>{CONTENT_DATA.transactionalTextTwelve}</li>
                    <li>{CONTENT_DATA.transactionalTextThirteen}</li>
                    <li>{CONTENT_DATA.transactionalFourteen}</li>
                    <li>{CONTENT_DATA.transactionalFifteen}</li>
                </ul>
                <h4>{CONTENT_DATA.profileSubtitle}</h4>
                <ul>
                    <li>{CONTENT_DATA.profileTextOne}</li>
                    <li>{CONTENT_DATA.profileTextTwo}</li>
                    <li>{CONTENT_DATA.profileTextThree}</li>
                    <li>{CONTENT_DATA.profileTextFour}</li>
                    <li>{CONTENT_DATA.profileTextFive}</li>
                    <li>{CONTENT_DATA.profileTextSix}</li>
                </ul>
                <h4>{CONTENT_DATA.usageDataSubtitle}</h4>
                <p>{CONTENT_DATA.usageDataTextOne}</p>
                <ul>
                    <li>{CONTENT_DATA.usageDataTextTwo}</li>
                    <li>{CONTENT_DATA.usageDataTextThree}</li>
                    <li>{CONTENT_DATA.usageDataTextFour}</li>
                    <li>{CONTENT_DATA.usageDataTextFive}</li>
                </ul>
                <h4>{CONTENT_DATA.marketingSubtitle}</h4>
                <ul>
                    <li>{CONTENT_DATA.marketingTextOne}</li>
                    <li>{CONTENT_DATA.marketingTextTwo}</li>
                </ul>
                <p>{CONTENT_DATA.marketingTextThree}</p>
                <p>{CONTENT_DATA.marketingTextFour}</p>
                <h4>{CONTENT_DATA.refuseSubtitle}</h4>
                <p>{CONTENT_DATA.refuseTextOne}</p>
                <h3>{CONTENT_DATA.informationCollectedSubtitle}</h3>
                <p>{CONTENT_DATA.informationCollectedTextOne}</p>
                <p>{CONTENT_DATA.informationCollectedTextTwo}</p>
                <ul>
                    <li>{CONTENT_DATA.informationCollectedTextThree}</li>
                    <li>{CONTENT_DATA.informationCollectedTextFour} </li>
                    <li>{CONTENT_DATA.informationCollectedTextFive}</li>
                    <li>{CONTENT_DATA.informationCollectedTextSix}</li>
                    <li>{CONTENT_DATA.informationCollectedTextSeven}</li>
                    <li>{CONTENT_DATA.informationCollectedTextEight}</li>
                    <li>{CONTENT_DATA.informationCollectedTextNine}</li>
                    <li>{CONTENT_DATA.informationCollectedTextTen}</li>
                </ul>
                <h4>{CONTENT_DATA.automatedTechnologiesSubtitle}</h4>
                <p>{CONTENT_DATA.automatedTechnologiesTextOne}</p>
                <h4>{CONTENT_DATA.thirdPartiesSubtitle}</h4>
                <p>{CONTENT_DATA.thirdPartiesTextOne}</p>
                <ul>
                    <li>{CONTENT_DATA.thirdPartiesTextTwo}</li>
                    <li>{CONTENT_DATA.thirdPartiesTextThree}</li>
                    <li>{CONTENT_DATA.thirdPartiesTextFour}</li>
                    <li>{CONTENT_DATA.thirdPartiesTextFive}</li>
                </ul>
                <h3>{CONTENT_DATA.personalInformationSubtitle}</h3>
                <p>{CONTENT_DATA.personalInformationTextOne}</p>
                <ul>
                    <li>{CONTENT_DATA.personalInformationTextTwo}</li>
                    <li>{CONTENT_DATA.personalInformationTextThree}</li>
                    <li>{CONTENT_DATA.personalInformationTextFour}</li>
                </ul>

                <h4>{CONTENT_DATA.personalInformationTextFive}</h4>
                <p>{CONTENT_DATA.personalInformationTextSix}</p>
                <ul>
                    <li>{CONTENT_DATA.personalInformationTextSeven}</li>
                    <li>{CONTENT_DATA.personalInformationTextEight}</li>
                    <li>{CONTENT_DATA.personalInformationTextNine}</li>
                    <li>{CONTENT_DATA.personalInformationTextTen}</li>
                    <li>{CONTENT_DATA.personalInformationTextEleven}</li>
                    <li>{CONTENT_DATA.personalInformationTextTwelve}</li>
                    <li>{CONTENT_DATA.personalInformationTextThirteen}</li>
                    <li>{CONTENT_DATA.personalInformationTextFourteen}</li>
                    <li>{CONTENT_DATA.personalInformationTextFifteen}</li>
                    <li>{CONTENT_DATA.personalInformationTextSixteen}</li>
                    <li>{CONTENT_DATA.personalInformationTextEighteen}</li>
                    <li>{CONTENT_DATA.personalInformationTextNighteen}</li>
                    <li>{CONTENT_DATA.personalInformationTextTwenty}</li>
                    <li>{CONTENT_DATA.personalInformationTextTwentyTwo}</li>
                    <li>{CONTENT_DATA.personalInformationTextTwentyThree}</li>
                    <li>{CONTENT_DATA.personalInformationTextTwentyFour}</li>
                    <li>{CONTENT_DATA.personalInformationTextTwentyFive}</li>
                </ul>
                <p>{CONTENT_DATA.personalInformationTextTwentySix}</p>
                <h4>{CONTENT_DATA.personalInformationSubtitlePromotional}</h4>
                <p>{CONTENT_DATA.personalInformationPromotionalTextOne}</p>
                <h4>{CONTENT_DATA.personalInformationSubtitleOpting}</h4>
                <p>{CONTENT_DATA.personalInformationOptingTextOne}</p>
                <p>{CONTENT_DATA.personalInformationOptingTextTwo}</p>
                <p>{CONTENT_DATA.personalInformationOptingTextThree}</p>
                <h4>{CONTENT_DATA.personalInformationSubtitleSale}</h4>
                <p>{CONTENT_DATA.personalInformationSaleTextOne}</p>
                <h3>{CONTENT_DATA.disclosuresPersonalInformationSubtitle}</h3>
                <p>{CONTENT_DATA.disclosuresPersonalInformationTextOne}</p>
                <ul>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextTwo}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextThree}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextFour}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextFive}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextSix} </li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextSeven}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextEight}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextNine}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextTen}</li>
                </ul>
                <p>{CONTENT_DATA.disclosuresPersonalInformationTextEleven}</p>
                <ul>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextTwelve}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextThirteen}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextFourteen}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextFifteen}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextSixteen}</li>
                    <li>{CONTENT_DATA.disclosuresPersonalInformationTextSeventeen}</li>
                </ul>
                <h3>{CONTENT_DATA.personalInformationSecuritySubtitle}</h3>
                <p>{CONTENT_DATA.personalInformationSecurityTextOne}</p>
                <p>{CONTENT_DATA.personalInformationSecurityTextTwo}</p>
                <p>{CONTENT_DATA.personalInformationSecurityTextThree}</p>
                <h3>{CONTENT_DATA.personalInformationRetentionSubtitle}</h3>
                <h4>{CONTENT_DATA.personalInformationRetentionTextOne}</h4>
                <p>{CONTENT_DATA.personalInformationRetentionTextTwo}</p>
                <p>{CONTENT_DATA.personalInformationRetentionTextThree}</p>
                <ul>
                    <li>{CONTENT_DATA.personalInformationRetentionTextFour} </li>
                    <li>{CONTENT_DATA.personalInformationRetentionTextFive}</li>
                    <li>{CONTENT_DATA.personalInformationRetentionTextSix}</li>
                    <li>{CONTENT_DATA.personalInformationRetentionTextSeven}</li>
                    <li>{CONTENT_DATA.personalInformationRetentionTextEight}</li>
                </ul>
                <p>{CONTENT_DATA.personalInformationRetentionTextNine}</p>
                <p>{CONTENT_DATA.personalInformationRetentionTextTen}</p>
                <h3>{CONTENT_DATA.legalRightsSubtitle}</h3>
                <p>{CONTENT_DATA.legalRightsTextOne} </p>
                <ul>
                    <li>{CONTENT_DATA.legalRightsTextTwo}</li>
                    <li>{CONTENT_DATA.legalRightsTextThree}</li>
                    <li>{CONTENT_DATA.legalRightsTextFour}</li>
                    <li>{CONTENT_DATA.legalRightsTextFive}</li>
                </ul>
                <p>{CONTENT_DATA.legalRightsTextSix}</p>
                <p>{CONTENT_DATA.legalRightsTextSeven}</p>
                <h4>{CONTENT_DATA.legalRightsTextEight}</h4>
                <p>{CONTENT_DATA.legalRightsTextNine}</p>

                <h4>{CONTENT_DATA.legalRightsTextTen}</h4>
                <p> {CONTENT_DATA.legalRightsTextEleven}</p>
            </>
        </InfoLayout>
    );
}
