export const countries = [
    { name: 'Afghanistan', phone: '93', iso2: 'AF' },
    { name: 'Aland Islands', phone: '+358-18', iso2: 'AX' },
    { name: 'Albania', phone: '355', iso2: 'AL' },
    { name: 'Algeria', phone: '213', iso2: 'DZ' },
    { name: 'American Samoa', phone: '+1-684', iso2: 'AS' },
    { name: 'Andorra', phone: '376', iso2: 'AD' },
    { name: 'Angola', phone: '244', iso2: 'AO' },
    { name: 'Anguilla', phone: '+1-264', iso2: 'AI' },
    { name: 'Antarctica', phone: '672', iso2: 'AQ' },
    { name: 'Antigua And Barbuda', phone: '+1-268', iso2: 'AG' },
    { name: 'Argentina', phone: '54', iso2: 'AR' },
    { name: 'Armenia', phone: '374', iso2: 'AM' },
    { name: 'Aruba', phone: '297', iso2: 'AW' },
    { name: 'Australia', phone: '61', iso2: 'AU' },
    { name: 'Austria', phone: '43', iso2: 'AT' },
    { name: 'Azerbaijan', phone: '994', iso2: 'AZ' },
    { name: 'Bahrain', phone: '973', iso2: 'BH' },
    { name: 'Bangladesh', phone: '880', iso2: 'BD' },
    { name: 'Barbados', phone: '+1-246', iso2: 'BB' },
    { name: 'Belarus', phone: '375', iso2: 'BY' },
    { name: 'Belgium', phone: '32', iso2: 'BE' },
    { name: 'Belize', phone: '501', iso2: 'BZ' },
    { name: 'Benin', phone: '229', iso2: 'BJ' },
    { name: 'Bermuda', phone: '+1-441', iso2: 'BM' },
    { name: 'Bhutan', phone: '975', iso2: 'BT' },
    { name: 'Bolivia', phone: '591', iso2: 'BO' },
    { name: 'Bonaire, Sint Eustatius and Saba', phone: '599', iso2: 'BQ' },
    { name: 'Bosnia and Herzegovina', phone: '387', iso2: 'BA' },
    { name: 'Botswana', phone: '267', iso2: 'BW' },
    { name: 'Bouvet Island', phone: '0055', iso2: 'BV' },
    { name: 'Brazil', phone: '55', iso2: 'BR' },
    { name: 'British Indian Ocean Territory', phone: '246', iso2: 'IO' },
    { name: 'Brunei', phone: '673', iso2: 'BN' },
    { name: 'Bulgaria', phone: '359', iso2: 'BG' },
    { name: 'Burkina Faso', phone: '226', iso2: 'BF' },
    { name: 'Burundi', phone: '257', iso2: 'BI' },
    { name: 'Cambodia', phone: '855', iso2: 'KH' },
    { name: 'Cameroon', phone: '237', iso2: 'CM' },
    { name: 'Canada', phone: '1', iso2: 'CA' },
    { name: 'Cape Verde', phone: '238', iso2: 'CV' },
    { name: 'Cayman Islands', phone: '+1-345', iso2: 'KY' },
    { name: 'Central African Republic', phone: '236', iso2: 'CF' },
    { name: 'Chad', phone: '235', iso2: 'TD' },
    { name: 'Chile', phone: '56', iso2: 'CL' },
    { name: 'China', phone: '86', iso2: 'CN' },
    { name: 'Christmas Island', phone: '61', iso2: 'CX' },
    { name: 'Cocos (Keeling) Islands', phone: '61', iso2: 'CC' },
    { name: 'Colombia', phone: '57', iso2: 'CO' },
    { name: 'Comoros', phone: '269', iso2: 'KM' },
    { name: 'Congo', phone: '242', iso2: 'CG' },
    { name: 'Cook Islands', phone: '682', iso2: 'CK' },
    { name: 'Costa Rica', phone: '506', iso2: 'CR' },
    { name: "Cote D'Ivoire (Ivory Coast)", phone: '225', iso2: 'CI' },
    { name: 'Croatia', phone: '385', iso2: 'HR' },
    { name: 'Cuba', phone: '53', iso2: 'CU' },
    { name: 'Curaçao', phone: '599', iso2: 'CW' },
    { name: 'Cyprus', phone: '357', iso2: 'CY' },
    { name: 'Czech Republic', phone: '420', iso2: 'CZ' },
    { name: 'Democratic Republic of the Congo', phone: '243', iso2: 'CD' },
    { name: 'Denmark', phone: '45', iso2: 'DK' },
    { name: 'Djibouti', phone: '253', iso2: 'DJ' },
    { name: 'Dominica', phone: '+1-767', iso2: 'DM' },
    { name: 'Dominican Republic', phone: '+1-809 and 1-829', iso2: 'DO' },
    { name: 'East Timor', phone: '670', iso2: 'TL' },
    { name: 'Ecuador', phone: '593', iso2: 'EC' },
    { name: 'Egypt', phone: '20', iso2: 'EG' },
    { name: 'El Salvador', phone: '503', iso2: 'SV' },
    { name: 'Equatorial Guinea', phone: '240', iso2: 'GQ' },
    { name: 'Eritrea', phone: '291', iso2: 'ER' },
    { name: 'Estonia', phone: '372', iso2: 'EE' },
    { name: 'Ethiopia', phone: '251', iso2: 'ET' },
    { name: 'Falkland Islands', phone: '500', iso2: 'FK' },
    { name: 'Faroe Islands', phone: '298', iso2: 'FO' },
    { name: 'Fiji Islands', phone: '679', iso2: 'FJ' },
    { name: 'Finland', phone: '358', iso2: 'FI' },
    { name: 'France', phone: '33', iso2: 'FR' },
    { name: 'French Guiana', phone: '594', iso2: 'GF' },
    { name: 'French Polynesia', phone: '689', iso2: 'PF' },
    { name: 'French Southern Territories', phone: '262', iso2: 'TF' },
    { name: 'Gabon', phone: '241', iso2: 'GA' },
    { name: 'Gambia The', phone: '220', iso2: 'GM' },
    { name: 'Georgia', phone: '995', iso2: 'GE' },
    { name: 'Germany', phone: '49', iso2: 'DE' },
    { name: 'Ghana', phone: '233', iso2: 'GH' },
    { name: 'Gibraltar', phone: '350', iso2: 'GI' },
    { name: 'Greece', phone: '30', iso2: 'GR' },
    { name: 'Greenland', phone: '299', iso2: 'GL' },
    { name: 'Grenada', phone: '+1-473', iso2: 'GD' },
    { name: 'Guadeloupe', phone: '590', iso2: 'GP' },
    { name: 'Guam', phone: '+1-671', iso2: 'GU' },
    { name: 'Guatemala', phone: '502', iso2: 'GT' },
    { name: 'Guernsey and Alderney', phone: '+44-1481', iso2: 'GG' },
    { name: 'Guinea', phone: '224', iso2: 'GN' },
    { name: 'Guinea-Bissau', phone: '245', iso2: 'GW' },
    { name: 'Guyana', phone: '592', iso2: 'GY' },
    { name: 'Haiti', phone: '509', iso2: 'HT' },
    { name: 'Heard Island and McDonald Islands', phone: '672', iso2: 'HM' },
    { name: 'Honduras', phone: '504', iso2: 'HN' },
    { name: 'Hong Kong S.A.R.', phone: '852', iso2: 'HK' },
    { name: 'Hungary', phone: '36', iso2: 'HU' },
    { name: 'Iceland', phone: '354', iso2: 'IS' },
    { name: 'India', phone: '91', iso2: 'IN' },
    { name: 'Indonesia', phone: '62', iso2: 'ID' },
    { name: 'Iran', phone: '98', iso2: 'IR' },
    { name: 'Iraq', phone: '964', iso2: 'IQ' },
    { name: 'Ireland', phone: '353', iso2: 'IE' },
    { name: 'Israel', phone: '972', iso2: 'IL' },
    { name: 'Italy', phone: '39', iso2: 'IT' },
    { name: 'Jamaica', phone: '+1-876', iso2: 'JM' },
    { name: 'Japan', phone: '81', iso2: 'JP' },
    { name: 'Jersey', phone: '+44-1534', iso2: 'JE' },
    { name: 'Jordan', phone: '962', iso2: 'JO' },
    { name: 'Kazakhstan', phone: '7', iso2: 'KZ' },
    { name: 'Kenya', phone: '254', iso2: 'KE' },
    { name: 'Kiribati', phone: '686', iso2: 'KI' },
    { name: 'Kosovo', phone: '383', iso2: 'XK' },
    { name: 'Kuwait', phone: '965', iso2: 'KW' },
    { name: 'Kyrgyzstan', phone: '996', iso2: 'KG' },
    { name: 'Laos', phone: '856', iso2: 'LA' },
    { name: 'Latvia', phone: '371', iso2: 'LV' },
    { name: 'Lebanon', phone: '961', iso2: 'LB' },
    { name: 'Lesotho', phone: '266', iso2: 'LS' },
    { name: 'Liberia', phone: '231', iso2: 'LR' },
    { name: 'Libya', phone: '218', iso2: 'LY' },
    { name: 'Liechtenstein', phone: '423', iso2: 'LI' },
    { name: 'Lithuania', phone: '370', iso2: 'LT' },
    { name: 'Luxembourg', phone: '352', iso2: 'LU' },
    { name: 'Macau S.A.R.', phone: '853', iso2: 'MO' },
    { name: 'Macedonia', phone: '389', iso2: 'MK' },
    { name: 'Madagascar', phone: '261', iso2: 'MG' },
    { name: 'Malawi', phone: '265', iso2: 'MW' },
    { name: 'Malaysia', phone: '60', iso2: 'MY' },
    { name: 'Maldives', phone: '960', iso2: 'MV' },
    { name: 'Mali', phone: '223', iso2: 'ML' },
    { name: 'Malta', phone: '356', iso2: 'MT' },
    { name: 'Man (Isle of)', phone: '+44-1624', iso2: 'IM' },
    { name: 'Marshall Islands', phone: '692', iso2: 'MH' },
    { name: 'Martinique', phone: '596', iso2: 'MQ' },
    { name: 'Mauritania', phone: '222', iso2: 'MR' },
    { name: 'Mauritius', phone: '230', iso2: 'MU' },
    { name: 'Mayotte', phone: '262', iso2: 'YT' },
    { name: 'Mexico', phone: '52', iso2: 'MX' },
    { name: 'Micronesia', phone: '691', iso2: 'FM' },
    { name: 'Moldova', phone: '373', iso2: 'MD' },
    { name: 'Monaco', phone: '377', iso2: 'MC' },
    { name: 'Mongolia', phone: '976', iso2: 'MN' },
    { name: 'Montenegro', phone: '382', iso2: 'ME' },
    { name: 'Montserrat', phone: '+1-664', iso2: 'MS' },
    { name: 'Morocco', phone: '212', iso2: 'MA' },
    { name: 'Mozambique', phone: '258', iso2: 'MZ' },
    { name: 'Myanmar', phone: '95', iso2: 'MM' },
    { name: 'Namibia', phone: '264', iso2: 'NA' },
    { name: 'Nauru', phone: '674', iso2: 'NR' },
    { name: 'Nepal', phone: '977', iso2: 'NP' },
    { name: 'Netherlands', phone: '31', iso2: 'NL' },
    { name: 'New Caledonia', phone: '687', iso2: 'NC' },
    { name: 'New Zealand', phone: '64', iso2: 'NZ' },
    { name: 'Nicaragua', phone: '505', iso2: 'NI' },
    { name: 'Niger', phone: '227', iso2: 'NE' },
    { name: 'Nigeria', phone: '234', iso2: 'NG' },
    { name: 'Niue', phone: '683', iso2: 'NU' },
    { name: 'Norfolk Island', phone: '672', iso2: 'NF' },
    { name: 'North Korea', phone: '850', iso2: 'KP' },
    { name: 'Northern Mariana Islands', phone: '+1-670', iso2: 'MP' },
    { name: 'Norway', phone: '47', iso2: 'NO' },
    { name: 'Oman', phone: '968', iso2: 'OM' },
    { name: 'Pakistan', phone: '92', iso2: 'PK' },
    { name: 'Palau', phone: '680', iso2: 'PW' },
    { name: 'Palestinian Territory Occupied', phone: '970', iso2: 'PS' },
    { name: 'Panama', phone: '507', iso2: 'PA' },
    { name: 'Papua new Guinea', phone: '675', iso2: 'PG' },
    { name: 'Paraguay', phone: '595', iso2: 'PY' },
    { name: 'Peru', phone: '51', iso2: 'PE' },
    { name: 'Philippines', phone: '63', iso2: 'PH' },
    { name: 'Pitcairn Island', phone: '870', iso2: 'PN' },
    { name: 'Poland', phone: '48', iso2: 'PL' },
    { name: 'Portugal', phone: '351', iso2: 'PT' },
    { name: 'Puerto Rico', phone: '+1-787 and 1-939', iso2: 'PR' },
    { name: 'Qatar', phone: '974', iso2: 'QA' },
    { name: 'Reunion', phone: '262', iso2: 'RE' },
    { name: 'Romania', phone: '40', iso2: 'RO' },
    { name: 'Russia', phone: '7', iso2: 'RU' },
    { name: 'Rwanda', phone: '250', iso2: 'RW' },
    { name: 'Saint Helena', phone: '290', iso2: 'SH' },
    { name: 'Saint Kitts And Nevis', phone: '+1-869', iso2: 'KN' },
    { name: 'Saint Lucia', phone: '+1-758', iso2: 'LC' },
    { name: 'Saint Pierre and Miquelon', phone: '508', iso2: 'PM' },
    { name: 'Saint Vincent And The Grenadines', phone: '+1-784', iso2: 'VC' },
    { name: 'Saint-Barthelemy', phone: '590', iso2: 'BL' },
    { name: 'Saint-Martin (French part)', phone: '590', iso2: 'MF' },
    { name: 'Samoa', phone: '685', iso2: 'WS' },
    { name: 'San Marino', phone: '378', iso2: 'SM' },
    { name: 'Sao Tome and Principe', phone: '239', iso2: 'ST' },
    { name: 'Saudi Arabia', phone: '966', iso2: 'SA' },
    { name: 'Senegal', phone: '221', iso2: 'SN' },
    { name: 'Serbia', phone: '381', iso2: 'RS' },
    { name: 'Seychelles', phone: '248', iso2: 'SC' },
    { name: 'Sierra Leone', phone: '232', iso2: 'SL' },
    { name: 'Singapore', phone: '65', iso2: 'SG' },
    { name: 'Sint Maarten (Dutch part)', phone: '1721', iso2: 'SX' },
    { name: 'Slovakia', phone: '421', iso2: 'SK' },
    { name: 'Slovenia', phone: '386', iso2: 'SI' },
    { name: 'Solomon Islands', phone: '677', iso2: 'SB' },
    { name: 'Somalia', phone: '252', iso2: 'SO' },
    { name: 'South Africa', phone: '27', iso2: 'ZA' },
    { name: 'South Georgia', phone: '500', iso2: 'GS' },
    { name: 'South Korea', phone: '82', iso2: 'KR' },
    { name: 'South Sudan', phone: '211', iso2: 'SS' },
    { name: 'Spain', phone: '34', iso2: 'ES' },
    { name: 'Sri Lanka', phone: '94', iso2: 'LK' },
    { name: 'Sudan', phone: '249', iso2: 'SD' },
    { name: 'Suriname', phone: '597', iso2: 'SR' },
    { name: 'Svalbard And Jan Mayen Islands', phone: '47', iso2: 'SJ' },
    { name: 'Swaziland', phone: '268', iso2: 'SZ' },
    { name: 'Sweden', phone: '46', iso2: 'SE' },
    { name: 'Switzerland', phone: '41', iso2: 'CH' },
    { name: 'Syria', phone: '963', iso2: 'SY' },
    { name: 'Taiwan', phone: '886', iso2: 'TW' },
    { name: 'Tajikistan', phone: '992', iso2: 'TJ' },
    { name: 'Tanzania', phone: '255', iso2: 'TZ' },
    { name: 'Thailand', phone: '66', iso2: 'TH' },
    { name: 'The Bahamas', phone: '+1-242', iso2: 'BS' },
    { name: 'Togo', phone: '228', iso2: 'TG' },
    { name: 'Tokelau', phone: '690', iso2: 'TK' },
    { name: 'Tonga', phone: '676', iso2: 'TO' },
    { name: 'Trinidad And Tobago', phone: '+1-868', iso2: 'TT' },
    { name: 'Tunisia', phone: '216', iso2: 'TN' },
    { name: 'Turkey', phone: '90', iso2: 'TR' },
    { name: 'Turkmenistan', phone: '993', iso2: 'TM' },
    { name: 'Turks And Caicos Islands', phone: '+1-649', iso2: 'TC' },
    { name: 'Tuvalu', phone: '688', iso2: 'TV' },
    { name: 'Uganda', phone: '256', iso2: 'UG' },
    { name: 'Ukraine', phone: '380', iso2: 'UA' },
    { name: 'United Arab Emirates', phone: '971', iso2: 'AE' },
    { name: 'United Kingdom', phone: '44', iso2: 'GB' },
    { name: 'United States', phone: '1', iso2: 'US' },
    { name: 'United States Minor Outlying Islands', phone: '1', iso2: 'UM' },
    { name: 'Uruguay', phone: '598', iso2: 'UY' },
    { name: 'Uzbekistan', phone: '998', iso2: 'UZ' },
    { name: 'Vanuatu', phone: '678', iso2: 'VU' },
    { name: 'Vatican City State (Holy See)', phone: '379', iso2: 'VA' },
    { name: 'Venezuela', phone: '58', iso2: 'VE' },
    { name: 'Vietnam', phone: '84', iso2: 'VN' },
    { name: 'Virgin Islands (British)', phone: '+1-284', iso2: 'VG' },
    { name: 'Virgin Islands (US)', phone: '+1-340', iso2: 'VI' },
    { name: 'Wallis And Futuna Islands', phone: '681', iso2: 'WF' },
    { name: 'Western Sahara', phone: '212', iso2: 'EH' },
    { name: 'Yemen', phone: '967', iso2: 'YE' },
    { name: 'Zambia', phone: '260', iso2: 'ZM' },
    { name: 'Zimbabwe', phone: '263', iso2: 'ZW' },
];
