const StringEng = {
    offerCreated: 'Offer created successfully',
    shareLink: 'Share Link',
    viewOfer: 'View offer',
    close: 'Close',
    copy: 'Copy',
    sellingPrice: 'Selling Price',
    totalCost: 'Total cost for buyer',
    setOffer: 'Set offer to private',
    youCanset: 'you can set it to public later',
    continue: 'Continue',
    cancel: 'Cancel',
    youAre: 'You are going to create a shareable offer for the following product',
    shipmentFrom: 'Shipment From',
    createANew: 'Create a new offer',
    setUp: 'Set up your offer’s details',
    condition: 'Condition',
    blockchain: 'Blockchain',
    category: 'Category',
    quantity: 'Quantity',
    purchaseThis: 'Purchase this item',
    description: 'Description',
    intenTo: 'Intent to Purchase',
    weNeedYour: 'We need your shipping information before we send this to the buyer.',
    previewYour: 'Preview your offer',
    expiresin: 'Expires in',
    shippingFrom: 'Shipping From',
    shipmentCost: 'Shipment Cost Included',
    available: 'Available',
    productDescription: 'Description',
    createOffer: 'Create Offer',
    editOffer: 'Edit Offer',
};
export default StringEng;
